# Generated by Django 3.1 on 2021-10-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockinout',
            name='total_hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
