# Generated by Django 3.1 on 2021-10-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211019_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockinout',
            name='total_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
