# Generated by Django 3.1 on 2021-10-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211019_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockinout',
            name='total_hour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
