# Generated by Django 3.1 on 2021-10-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211019_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockinout',
            name='clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
